<?php
/**
 * TL_ROOT/system/modules/news_related/languages/fa/tl_module.php 
 * 
 * Contao extension: news_related 3.5.3 
 * Persian translation file 
 * 
 * Copyright : &copy; 2013-2017 Fast End Media 
 * License   : LGPL 
 * Author    : Fast & Media (Stranger), https://www.fast-end-media.de 
 * Translator: Hamid Abbaszadeh (respinar), https://respinar.com 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['related_numberOfItems']['0'] = "تعداد ورودی‌های مشابه";
$GLOBALS['TL_LANG']['tl_module']['related_numberOfItems']['1'] = "چه تعداد ورودی‌های مشابه می‌خواهید نمایش داده شود؟";
$GLOBALS['TL_LANG']['tl_module']['related_template']['0'] = "قالب برای اخبار مرتبط";
$GLOBALS['TL_LANG']['tl_module']['related_template']['1'] = "اینجا می‌توانید قالب اخبار مرتبط را انتخاب نمایید.";
$GLOBALS['TL_LANG']['tl_module']['related_legend'] = "ورودی‌های مرتبط";
 
?>
